namespace EntityBuilders;

internal static class EntityBuilderTemplate
{
    public static string GenerateSource(Entity entity, EntityBuilderConfig config)
    {
        var propertyMethods = string.Join(string.Empty, entity.Properties.Select(property => $@"
        public {property.Entity.Name}Builder {property.Name}({property.PropertyType} value){{
            _entity.{property.Name} = value;
            return this;
        }}
"));

        return $@"// <auto-generated />
using {entity.Namespace};

namespace {config.RootNamespace}
{{
    public partial class {entity.Name}Builder
    {{
        private readonly {entity.Name} _entity;

        public {entity.Name} Entity {{ get
            {{
                return _entity;
            }}
        }}

        public {entity.Name}Builder(IIdProvider idProvider)
        {{
            _entity = new {entity.Name}();
            this.{entity.IdPropertyName}(idProvider.NewId());
        }}

        #region Property Methods
        {propertyMethods}
        #endregion
    }}
}}
";
    }
}