namespace EntityBuilders;

internal static class IdProvidersTemplate
{
    public static string GenerateSource(EntityBuilderConfig config)
    {
        return @$"// <auto-generated />
namespace {config.RootNamespace}
{{
    public interface IIdProvider
    {{
        int NewId();
    }}

    public class SequentialProvider : IIdProvider
    {{
        private int Count;

        public int NewId()
        {{
            return ++Count;
        }}
    }}
}}
";
    }
}