using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EntityBuilders;

internal static class IdProvidersGenerator
{
    public static void AddSource(GeneratorExecutionContext context, EntityBuilderConfig config)
    {
        context.AddSource("IIdProvider.g.cs", SourceText.From(@$"// <auto-generated />
namespace {config.RootNamespace}
{{
    public interface IIdProvider
    {{
        int NewId();
    }}

    public class SequentialProvider : IIdProvider
    {{
        private int Count;

        public int NewId()
        {{
            return ++Count;
        }}
    }}
}}
", Encoding.UTF8));
    }
}